/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Connection.ConnectToSQL;
import Connection.quanli;
import ThuocTinh.HangXe;
import ThuocTinh.LoaiXe;
import ThuocTinh.MauXe;
import ThuocTinh.XeMay;
import doan.login;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class TrangChu extends javax.swing.JFrame {
    
    //hãng xe
    Vector data = new Vector();//khởi tạo mảng trống
    ArrayList<HangXe> ql_hang = new ArrayList<>();
    quanli quanlixe = new quanli();
    HangXe hang = new HangXe();// tạo 1 nơi lưu thông tin nhập vào
    DefaultTableModel md = new DefaultTableModel();

    //loại xe
    Vector data_loai = new Vector();
    ArrayList<LoaiXe> ql_loai = new ArrayList<>();
    LoaiXe loai = new LoaiXe();

    //mau xe
    Vector data_mau = new Vector();
    ArrayList<MauXe> ql_mau = new ArrayList<>();
    MauXe mau = new MauXe();

    //xe máy
    Vector data_xe = new Vector();
    ArrayList<XeMay> ob_x = new ArrayList<>();
    XeMay xe_may_e = new XeMay();
    ArrayList<HangXe> hxp = new ArrayList<>();
    ArrayList<LoaiXe> lxp = new ArrayList<>();
    ArrayList<MauXe> mxp = new ArrayList<>();
    //String ImgPath;
    
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quanli = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableXe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MaXe = new javax.swing.JTextField();
        TenXe = new javax.swing.JTextField();
        ComboMau = new javax.swing.JComboBox<>();
        ComboLoai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TonKho = new javax.swing.JTextField();
        SoKhung = new javax.swing.JTextField();
        Gia = new javax.swing.JTextField();
        Upadte = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        DungTich = new javax.swing.JTextField();
        ComboHang = new javax.swing.JComboBox<>();
        AddXe = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableMau = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MaMau = new javax.swing.JTextField();
        TenMau = new javax.swing.JTextField();
        Them_Mau = new javax.swing.JButton();
        Xoa_Mau = new javax.swing.JButton();
        Rs_Mau = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHang = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MaHang = new javax.swing.JTextField();
        TenHang = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ThongTinHang = new javax.swing.JTextArea();
        Them_Hang = new javax.swing.JButton();
        Sua_Hang = new javax.swing.JButton();
        Xoa_Hang = new javax.swing.JButton();
        rs_hang = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableLoai = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        MaLoai = new javax.swing.JTextField();
        TenLoai = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        ThongTinLoai = new javax.swing.JTextArea();
        Them_Loai = new javax.swing.JButton();
        Sua_Loai = new javax.swing.JButton();
        Xoa_Loai = new javax.swing.JButton();
        Rs_loai = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        TableXe.setAutoCreateRowSorter(true);
        TableXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã xe", "Tên xe", "Màu xe", "Loại xe", "Hãng sản xuất", "Tồn kho", "Số khung", "Giá nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableXe.setShowGrid(true);
        TableXe.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(TableXe);
        if (TableXe.getColumnModel().getColumnCount() > 0) {
            TableXe.getColumnModel().getColumn(0).setMinWidth(10);
            TableXe.getColumnModel().getColumn(0).setMaxWidth(40);
            TableXe.getColumnModel().getColumn(5).setMinWidth(100);
            TableXe.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        jLabel1.setText("Mã xe:");

        jLabel2.setText("Tên xe:");

        jLabel3.setText("Màu xe: ");

        jLabel4.setText("Loại xe: ");

        ComboMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Hãng sản xuất:");

        jLabel6.setText("Tồn kho:");

        jLabel7.setText("Số khung:");

        jLabel8.setText("Giá nhập:");

        Upadte.setText("Sửa");
        Upadte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpadteActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jLabel10.setText("Dung tích:");

        ComboHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddXe.setText("Thêm");
        AddXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddXeActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TenXe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addComponent(MaXe, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SoKhung)
                            .addComponent(Gia)
                            .addComponent(DungTich)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TonKho, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Upadte)
                    .addComponent(Delete)
                    .addComponent(AddXe)
                    .addComponent(Reset))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ComboHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddXe))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(SoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upadte))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DungTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset))
                .addGap(63, 63, 63))
        );

        Quanli.addTab("Quản lí kho xe", jPanel1);

        TableMau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã màu", "Tên màu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMau.setShowGrid(true);
        TableMau.setShowHorizontalLines(true);
        TableMau.setShowVerticalLines(true);
        TableMau.setSurrendersFocusOnKeystroke(true);
        jScrollPane4.setViewportView(TableMau);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mã màu:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tên màu:");

        TenMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenMauActionPerformed(evt);
            }
        });

        Them_Mau.setText("Thêm màu");
        Them_Mau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Them_MauActionPerformed(evt);
            }
        });

        Xoa_Mau.setText("Xoá màu");
        Xoa_Mau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xoa_MauActionPerformed(evt);
            }
        });

        Rs_Mau.setText("Reset");
        Rs_Mau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rs_MauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenMau, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rs_Mau)
                    .addComponent(Xoa_Mau)
                    .addComponent(Them_Mau))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Them_Mau))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TenMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa_Mau))
                .addGap(28, 28, 28)
                .addComponent(Rs_Mau)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        Quanli.addTab("Màu", jPanel3);

        TableHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hãng", "Tên hãng", "Thông tin"
            }
        ));
        TableHang.setShowGrid(true);
        TableHang.setShowVerticalLines(true);
        TableHang.setSurrendersFocusOnKeystroke(true);
        TableHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableHang);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã hãng:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tên hãng:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Thông tin về hãng:");

        TenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenHangActionPerformed(evt);
            }
        });

        ThongTinHang.setColumns(20);
        ThongTinHang.setRows(5);
        jScrollPane3.setViewportView(ThongTinHang);

        Them_Hang.setText("Thêm hãng xe");
        Them_Hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Them_HangActionPerformed(evt);
            }
        });

        Sua_Hang.setText("Sửa hãng xe");
        Sua_Hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sua_HangActionPerformed(evt);
            }
        });

        Xoa_Hang.setText("Xoá hãng xe");
        Xoa_Hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xoa_HangActionPerformed(evt);
            }
        });

        rs_hang.setText("Reset");
        rs_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs_hangActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Xoa_Hang)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Them_Hang)
                            .addComponent(Sua_Hang))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(rs_hang))))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Them_Hang)
                    .addComponent(rs_hang))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sua_Hang)
                    .addComponent(jButton5))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa_Hang))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        Quanli.addTab("Hãng", jPanel2);

        TableLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableLoai.setShowGrid(true);
        TableLoai.setShowHorizontalLines(true);
        TableLoai.setShowVerticalLines(true);
        TableLoai.setSurrendersFocusOnKeystroke(true);
        jScrollPane5.setViewportView(TableLoai);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Mã loại:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tên loại:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Thông tin về loại:");

        TenLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenLoaiActionPerformed(evt);
            }
        });

        ThongTinLoai.setColumns(20);
        ThongTinLoai.setRows(5);
        jScrollPane6.setViewportView(ThongTinLoai);

        Them_Loai.setText("Thêm loại xe");
        Them_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Them_LoaiActionPerformed(evt);
            }
        });

        Sua_Loai.setText("Sửa loại xe");
        Sua_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sua_LoaiActionPerformed(evt);
            }
        });

        Xoa_Loai.setText("Xoá loại xe");
        Xoa_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xoa_LoaiActionPerformed(evt);
            }
        });

        Rs_loai.setText("Reset");
        Rs_loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rs_loaiActionPerformed(evt);
            }
        });

        jButton6.setText("jButton5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Xoa_Loai)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Them_Loai)
                            .addComponent(Sua_Loai))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(Rs_loai))))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Them_Loai)
                    .addComponent(Rs_loai))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sua_Loai)
                    .addComponent(jButton6))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa_Loai))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        Quanli.addTab("Loại", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quanli, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Quanli)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rs_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs_hangActionPerformed
        clear();
    }//GEN-LAST:event_rs_hangActionPerformed

    private void Xoa_HangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xoa_HangActionPerformed
        boolean check = true;
        ql_hang = quanlixe.getDataHang();
        int row = TableHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Chọn Ô Hãng Xe Để Xóa Hãng Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            int click=JOptionPane.showConfirmDialog(this, "Bạn Có Chắc Chắn Muốn Xóa","Thông Báo",JOptionPane.YES_NO_OPTION);
            if(click==JOptionPane.YES_OPTION){
                if (login.id_role == 1) {

                    if (quanlixe.delete_hang(ql_hang.get(row).getMa_Hang())) {
                        JOptionPane.showMessageDialog(this, "Xóa Hãng Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        rs_hangActionPerformed(evt);
                        getDL();// xuất dữ liệu của hãng ra danh sách
                    } else {
                        JOptionPane.showMessageDialog(this, "Lỗi Xóa Hãng Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this, "Bạn Chưa Có Quyền Xóa", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_Xoa_HangActionPerformed

    private void Sua_HangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sua_HangActionPerformed
        ql_hang = quanlixe.getDataHang();
        boolean check = true;
        String ten = TenHang.getText();
        String thongtin = ThongTinHang.getText();

        int row = TableHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Chọn Ô Hãng Xe Để Sửa Thông Tin Hãng Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            HangXe hang = new HangXe();
            hang.setTen_Hang(ten);
            hang.setThong_Tin(thongtin);
            hang.setMa_Hang(ql_hang.get(row).getMa_Hang());
            if (quanlixe.update_hang(hang)) {
                JOptionPane.showMessageDialog(this, "Sửa Hãng Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                clear();
                getDL();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Sửa Hãng Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Sua_HangActionPerformed

    private void Them_HangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Them_HangActionPerformed
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ma = MaHang.getText();
        String ten = TenHang.getText();
        String thongtin = ThongTinHang.getText();
        String check_hang = "SELECT Hang_xe.Ten_hang FROM Hang_xe WHERE Ten_hang='" + ten + "'";

        if (ma.equals("") || ten.equals("") || thongtin.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Nhập Thông Tin Để Thêm Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            conn = ConnectToSQL.openConnection();
            try {
                pst = conn.prepareCall(check_hang);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Tên Hãng Xe Đã Tồn Tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    hang.setMa_Hang(ma);
                    hang.setTen_Hang(ten);
                    hang.setThong_Tin(thongtin);
                    if (quanlixe.add_hang(hang)) {
                        JOptionPane.showMessageDialog(this, "Thêm Hãng Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        clear();
                        getDL();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lỗi Thêm Hãng Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Them_HangActionPerformed

    private void TenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenHangActionPerformed

    private void AddXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddXeActionPerformed
        ql_hang = quanlixe.getDataHang();
        //ql_loai = quanlixe.getLoaiDT();
        ql_mau = quanlixe.getDataMau();
        boolean check = true;
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ma = MaXe.getText();
        String ten_xe = TenXe.getText();
        String gia_xe = Gia.getText();
        String ton_kho = TonKho.getText();
        //hang
        int rowHang = ComboHang.getSelectedIndex();
        String idHang = ql_hang.get(rowHang).getMa_Hang();
        //loai
        int loai = ComboLoai.getSelectedIndex();
        String idLoai = ql_loai.get(loai).getMa_Loai();
        //mau
        int rowMau = ComboMau.getSelectedIndex();
        String idMau = ql_mau.get(rowMau).getMa_Mau();
        float gia = 0;
        int kho=0;
        String sokhung = SoKhung.getText();
        String dungtich = DungTich.getText();

        //kiem tra xe da ton tai
        String check_xe = "SELECT * FROM Xe_may Where Ten_xe='" + ten_xe + "'";
        if (ten_xe.equals("") || gia_xe.equals("") || sokhung.equals("") || dungtich.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đầy Đủ Thông Tin", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                gia = Float.parseFloat(gia_xe);
                check = true;
            } catch (Exception e) {
                check = false;
                JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đúng Giá Tiền Là Số", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                kho=Integer.parseInt(ton_kho);
                check=true;
            } catch (Exception e) {
                check=false;
                JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đúng Tồn Kho Là Số", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            conn = ConnectToSQL.openConnection();
            try {
                pst = conn.prepareCall(check_xe);
                rs = pst.executeQuery();
                if (rs.next() && check == true) {
                    JOptionPane.showMessageDialog(this, "Tên Xe Bạn Thêm Đã Tồn Tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else if (check == true) {
                    //InputStream img = new FileInputStream(new File(ImgPath));
                    XeMay xe_may = new XeMay();
                    xe_may.setMa_Xe(ma);
                    xe_may.setTen_Xe(ten_xe);
                    xe_may.setGia(gia);
                    xe_may.setMa_Hang(idHang);
                    xe_may.setMa_Loai(idLoai);
                    xe_may.setMa_Mau(idMau);
                    //xe_may.setAnh_xe(img);
                    xe_may.setSo_Khung(sokhung);
                    xe_may.setDung_Tich(dungtich);
                    xe_may.setTon_Kho(kho);

                    if (quanlixe.add_xe_may(xe_may)) {
                        JOptionPane.showMessageDialog(this, "Thêm Xe Máy Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        getXeMay();
                        ResetActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "Lỗi Thêm Xe Máy", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_AddXeActionPerformed
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpadteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpadteActionPerformed
        boolean check = true;
        ob_x = quanlixe.getDL_xe();
        ql_hang = quanlixe.getDataHang();
        //ql_loai = quanlixe.getLoaiDT();
        ql_mau = quanlixe.getDataMau();
        String ten_xe = TenXe.getText();
        String gia_xe = Gia.getText();
        //hang
        int rowHang = ComboHang.getSelectedIndex();
        String idHang = ql_hang.get(rowHang).getMa_Hang();

        //loai
        int loai = ComboLoai.getSelectedIndex();
        String idLoai = ql_loai.get(loai).getMa_Loai();
        //mau
        int rowMau = ComboMau.getSelectedIndex();
        String idMau = ql_mau.get(rowMau).getMa_Mau();
        float gia = 0;
        String tonst = TonKho.getText();
        int kho=0;

        String sokhung = SoKhung.getText();
        String dungtich = DungTich.getText();

        int row = TableXe.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Chọn Ô Xe Máy Để Sửa Thông Tin Xe Máy", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            try {
                gia = Float.parseFloat(gia_xe);
                check = true;
            } catch (Exception e) {
                check = false;
                JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đúng Giá Tiền Là Số", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            try {
                kho=Integer.parseInt(tonst);
                check=true;
            } catch (Exception e) {
                check = false;
                JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đúng Tồn Kho Là Số", "ERROR", JOptionPane.ERROR_MESSAGE);

            } 
            XeMay xe_may = new XeMay();
            xe_may.setTen_Xe(ten_xe);
            xe_may.setGia(gia);
            xe_may.setMa_Loai(idLoai);
            xe_may.setMa_Mau(idMau);
            xe_may.setMa_Hang(idHang);
            xe_may.setSo_Khung(sokhung);
            xe_may.setDung_Tich(dungtich);
            xe_may.setTon_Kho(kho);
            xe_may.setMa_Xe(ob_x.get(row).getMa_Xe());
            if (quanlixe.update_xe(xe_may)) {
                JOptionPane.showMessageDialog(jLabel14, "Sửa Thông Tin Xe Máy Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                getXeMay();
                ResetActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(jLabel14, "Lỗi Sửa Xe Máy", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_UpadteActionPerformed

    private void TenMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenMauActionPerformed

    private void Them_MauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Them_MauActionPerformed
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ten = TenMau.getText();

        //kiểm tra tồn tại loại xe
        String ma = MaMau.getText();
        String check_mau = "SELECT * FROM Mauxe Where Mau_xe='" + ten + "'";

        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đầy Đủ Thông Tin Để Thêm Màu Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            conn = ConnectToSQL.openConnection();
            try {
                pst = conn.prepareCall(check_mau);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Màu Xe Bạn Thêm Đã Tồn Tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    mau.setMa_Mau(ma);
                    mau.setMau_Xe(ten);
                    if (quanlixe.add_mau_xe(mau)) {
                        JOptionPane.showMessageDialog(this, "Thêm Màu Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        TenMau.setText(null);
                        getDL_mau_xe();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lỗi Thêm Màu Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Them_MauActionPerformed

    private void Xoa_MauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xoa_MauActionPerformed
        boolean check = true;
        ql_mau = quanlixe.getDataMau();
        int row = TableMau.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Chọn Ô Màu Xe Để Xóa Màu Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            int click=JOptionPane.showConfirmDialog(this, "Bạn Có Chắc Chắn Muốn Xóa","Thông Báo",JOptionPane.YES_NO_OPTION);
                if(click==JOptionPane.YES_OPTION){
            if (login.id_role == 1) {
                 
                 if (quanlixe.delete_mau_xe(ql_mau.get(row).getMa_Mau())) {
                    JOptionPane.showMessageDialog(this, "Xóa Màu Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    TenMau.setText("");
                    getDL_mau_xe();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi Xóa Màu Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                }
             else {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Có Quyền Xóa", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
                }
        }
    }//GEN-LAST:event_Xoa_MauActionPerformed

    private void Rs_MauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rs_MauActionPerformed
        clear();
    }//GEN-LAST:event_Rs_MauActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        clear();
    }//GEN-LAST:event_ResetActionPerformed

    private void TenLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenLoaiActionPerformed

    private void Them_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Them_LoaiActionPerformed
        Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String ma_loai = MaLoai.getText();
        String ten_loai_xe = TenLoai.getText();
        String mo_ta = ThongTinLoai.getText();

        //kiểm tra tồn tại loại xe
        String check_loai = "SELECT * FROM Loai_xe Where Ten_loai_xe='" + ten_loai_xe + "'";

        if (ten_loai_xe.equals("") || mo_ta.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Đầy Đủ Thông Tin Để Thêm Loại Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            conn = ConnectToSQL.openConnection();
            try {
                pst = conn.prepareCall(check_loai);
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Loại Xe Bạn Thêm Đã Tồn Tại", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    loai.setMa_Loai(ma_loai);
                    loai.setTen_Loai(ten_loai_xe);
                    loai.setMota(mo_ta);
                    if (quanlixe.add_loai_xe(loai)) {
                        JOptionPane.showMessageDialog(this, "Thêm Loại Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        Rs_loaiActionPerformed(evt);
                        getLoaiXe();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lỗi Thêm Loại Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Them_LoaiActionPerformed

    private void Sua_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sua_LoaiActionPerformed
        ql_loai = quanlixe.getDataLoai();
        boolean check = true;
        String ten = TenLoai.getText();
        String thongtin = ThongTinLoai.getText();

        int row = TableLoai.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Chọn Ô Loại Xe Để Sửa Thông Tin Loại Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            LoaiXe lx = new LoaiXe();
            lx.setTen_Loai(ten);
            lx.setMota(thongtin);
            lx.setMa_Loai(ql_loai.get(row).getMa_Loai());
            if (quanlixe.update_loai_xe(lx)) {
                JOptionPane.showMessageDialog(this, "Sửa Loại Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                Rs_loaiActionPerformed(evt);
                getLoaiXe();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Sửa Loại Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Sua_LoaiActionPerformed

    private void Xoa_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xoa_LoaiActionPerformed
        boolean check = true;
        ql_loai = quanlixe.getDataLoai();
        int row = TableLoai.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn Cần Chọn Ô Loại Xe Để Xóa Loại Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
            check = false;
        } else if (check == true) {
            int click = JOptionPane.showConfirmDialog(this, "Bạn Có Chắc Chắn Muốn Xóa", "Thông Báo", JOptionPane.YES_NO_OPTION);
                if(click==JOptionPane.YES_OPTION){
            if (login.id_role == 1) {
                
                if (quanlixe.delete_loai_xe(ql_loai.get(row).getMa_Loai())) {
                    JOptionPane.showMessageDialog(this, "Xóa Loại Xe Thành Công", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    Rs_loaiActionPerformed(evt);
                    getLoaiXe();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi Xóa Loại Xe", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                }
             else {
                JOptionPane.showMessageDialog(this, "Bạn Chưa Có Quyền Xóa", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
                }
        }

    }//GEN-LAST:event_Xoa_LoaiActionPerformed

    private void Rs_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rs_loaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rs_loaiActionPerformed

    private void TableHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHangMouseClicked
        MaHang.setEditable(false);
        MaHang.setForeground(Color.red);
        MaHang.setBackground(new java.awt.Color(153, 153, 153));
        int row = TableHang.getSelectedRow();
        ql_hang = quanlixe.getDataHang();

        MaHang.setText(ql_hang.get(row).getMa_Hang());
        TenHang.setText(ql_hang.get(row).getTen_Hang());
        ThongTinHang.setText(ql_hang.get(row).getThong_Tin());
    }//GEN-LAST:event_TableHangMouseClicked
    
    public void clear() {
        MaHang.setEditable(true);
        //ma_hang.setForeground(Color.BLACK);
        //ma_hang.setBackground(new java.awt.Color(255, 255, 255));
        MaHang.setText(null);
        TenHang.setText(null);
        ThongTinHang.setText(null);
    }
    
    public void getLoaiXe() {

        ql_loai = quanlixe.getDataLoai();

        Vector col_loai = new Vector();
        data_loai = new Vector();

        int i = 1;
        col_loai.addElement("STT");
        col_loai.addElement("Mã Loại Xe");
        col_loai.addElement("Tên Loại Xe");
        col_loai.addElement("Mô Tả");

        for (LoaiXe ob : ql_loai) {
            Vector row_loai = new Vector();
            row_loai.add(i++);
            row_loai.add(ob.getMa_Loai());
            row_loai.add(ob.getTen_Loai());
            row_loai.add(ob.getMota());
            data_loai.add(row_loai);
        }

        md = new DefaultTableModel(data_loai, col_loai);
        TableLoai.setModel(md);

    }
    
    public void getDL_mau_xe() {
        ql_mau = quanlixe.getDataMau();
        Vector col_mau = new Vector();
        int i = 1;
        col_mau.add("STT");
        col_mau.add("Mã Màu");
        col_mau.add("Màu Xe");
        data_mau = new Vector();
        for (MauXe lk : ql_mau) {
            Vector row_mau = new Vector();
            row_mau.add(i++);
            row_mau.add(lk.getMa_Mau());
            row_mau.add(lk.getMau_Xe());
            data_mau.add(row_mau);
        }
        md = new DefaultTableModel(data_mau, col_mau);
        TableMau.setModel(md);
    }
    
    public void getDL() {
        ql_hang = quanlixe.getDataHang();
        int i = 1;
        Vector col = new Vector();

        data = new Vector();
        col.add("STT");
        col.add("Mã Hãng");
        col.add("Tên Hãng");
        col.add("Thông Tin Hãng");

        for (HangXe lo : ql_hang) {
            Vector row = new Vector();
            row.add(i++);
            row.add(lo.getMa_Hang());
            row.add(lo.getTen_Hang());
            row.add(lo.getThong_Tin());
            data.add(row);
        }
        md = new DefaultTableModel(data, col);
        TableHang.setModel(md);
    }
    
    public void getXeMay() {
        ob_x = quanlixe.getDL_xe();
        Vector col_xe = new Vector();
        data_xe = new Vector();

        int i = 1;
        col_xe.addElement("STT");
        col_xe.add("Mã Xe");
        col_xe.addElement("Tên Xe");
        col_xe.addElement("Giá");
        col_xe.addElement("Hãng Xe");
        col_xe.addElement("Loại Xe");
        col_xe.addElement("Màu Xe");
        col_xe.addElement("Số Khung");
        col_xe.addElement("Số Máy");
        col_xe.addElement("Dung Tích");
        col_xe.addElement("Số Lượng");
        NumberFormat fm = new DecimalFormat("#,###,###");
        for (XeMay lo : ob_x) {
            Vector row_xe = new Vector();
            row_xe.add(i++);
            row_xe.add(lo.getMa_Xe());
            row_xe.add(lo.getTen_Xe());
            row_xe.add(fm.format(lo.getGia()));

            //hang
            hxp = quanlixe.hangxe_id(lo.getMa_Hang());
            row_xe.add(hxp.get(0).getTen_Hang());
            //loai
            lxp = quanlixe.loaixe_id(lo.getMa_Loai());
            row_xe.add(lxp.get(0).getTen_Loai());

            //mau
            mxp = quanlixe.mauxe_id(lo.getMa_Mau());
            row_xe.add(mxp.get(0).getMau_Xe());
            
            row_xe.add(lo.getSo_Khung());
            row_xe.add(lo.getDung_Tich());
            row_xe.add(lo.getTon_Kho());
            data_xe.add(row_xe);
        }
        md = new DefaultTableModel(data_xe, col_xe);
        TableXe.setModel(md);
    }
    
    public void getCombo_HangXe() {
        ql_hang = quanlixe.getDataHang();
        for (HangXe ob : ql_hang) {
            ComboHang.addItem(ob.getTen_Hang());
        }
    }
    
    public void getCombo_Mauxe() {
        ql_mau = quanlixe.getDataMau();
        for (MauXe po : ql_mau) {
            ComboMau.addItem(po.getMau_Xe());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddXe;
    private javax.swing.JComboBox<String> ComboHang;
    private javax.swing.JComboBox<String> ComboLoai;
    private javax.swing.JComboBox<String> ComboMau;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DungTich;
    private javax.swing.JTextField Gia;
    private javax.swing.JTextField MaHang;
    private javax.swing.JTextField MaLoai;
    private javax.swing.JTextField MaMau;
    private javax.swing.JTextField MaXe;
    private javax.swing.JTabbedPane Quanli;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Rs_Mau;
    private javax.swing.JButton Rs_loai;
    private javax.swing.JTextField SoKhung;
    private javax.swing.JButton Sua_Hang;
    private javax.swing.JButton Sua_Loai;
    private javax.swing.JTable TableHang;
    private javax.swing.JTable TableLoai;
    private javax.swing.JTable TableMau;
    private javax.swing.JTable TableXe;
    private javax.swing.JTextField TenHang;
    private javax.swing.JTextField TenLoai;
    private javax.swing.JTextField TenMau;
    private javax.swing.JTextField TenXe;
    private javax.swing.JButton Them_Hang;
    private javax.swing.JButton Them_Loai;
    private javax.swing.JButton Them_Mau;
    private javax.swing.JTextArea ThongTinHang;
    private javax.swing.JTextArea ThongTinLoai;
    private javax.swing.JTextField TonKho;
    private javax.swing.JButton Upadte;
    private javax.swing.JButton Xoa_Hang;
    private javax.swing.JButton Xoa_Loai;
    private javax.swing.JButton Xoa_Mau;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton rs_hang;
    // End of variables declaration//GEN-END:variables
}
